services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.local.lab
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik-net
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_config:/etc/gitlab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.local.lab`)"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    networks:
      - traefik-net
    volumes:
      - registry_data:/var/lib/registry
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  runner:
    image: gitlab/gitlab-runner:latest
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_runner:/etc/gitlab-runner
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

volumes:
  gitlab_data:
  gitlab_logs:
  gitlab_config:
  registry_data:
  gitlab_runner:

networks:
  traefik-net:
    external: true